/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x0F000601U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0xD0070000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL_MASK 0x480001U /*!< GPIO3 and GPIO8 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL_MASK 0x997E021CU /*!< GPIO4 and GPIO9 share same IO MUX function, GPIO_MUX4 selects one GPIO function: affected bits mask */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_EMC_40 (coord A7), ENET_MDC */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_MDC_PERIPHERAL                                  ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_MDC_SIGNAL                                  enet_mdc   /*!< Signal name */

/* GPIO_EMC_41 (coord C7), ENET_MDIO */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_MDIO_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_MDIO_SIGNAL                                enet_mdio   /*!< Signal name */

/* GPIO_B1_10 (coord B13), ENET_TX_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TX_CLK_PERIPHERAL                               ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TX_CLK_SIGNAL                           enet_ref_clk   /*!< Signal name */

/* GPIO_B1_04 (coord E12), ENET_RXD0 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXD0_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXD0_SIGNAL                             enet_rx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RXD0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_B1_05 (coord D12), ENET_RXD1 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXD1_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXD1_SIGNAL                             enet_rx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RXD1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_B1_06 (coord C12), ENET_CRS_DV */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_CRS_DV_PERIPHERAL                               ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_CRS_DV_SIGNAL                             enet_rx_en   /*!< Signal name */

/* GPIO_B1_11 (coord C13), ENET_RXER */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXER_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXER_SIGNAL                               enet_rx_er   /*!< Signal name */

/* GPIO_B1_07 (coord B12), ENET_TXD0 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXD0_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXD0_SIGNAL                             enet_tx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_TXD0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_B1_08 (coord A12), ENET_TXD1 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXD1_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXD1_SIGNAL                             enet_tx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_TXD1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_B1_09 (coord A13), ENET_TXEN */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXEN_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXEN_SIGNAL                               enet_tx_en   /*!< Signal name */

/* GPIO_AD_B0_09 (coord F14), ENET_RST */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RST_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RST_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ENET_RST_CHANNEL                                       9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ENET_RST_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ENET_RST_GPIO_PIN                                      9U   /*!< GPIO pin number */
#define BOARD_INITPINS_ENET_RST_GPIO_PIN_MASK                         (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ENET_RST_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ENET_RST_PIN                                           9U   /*!< PORT pin number */
#define BOARD_INITPINS_ENET_RST_PIN_MASK                              (1U << 9U)   /*!< PORT pin mask */

/* GPIO_SD_B0_01 (coord J3), SD1_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_CLK_PERIPHERAL                                 USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_CLK_SIGNAL                                  usdhc_clk   /*!< Signal name */

/* GPIO_SD_B0_00 (coord J4), SD1_CMD */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_CMD_PERIPHERAL                                 USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_CMD_SIGNAL                                  usdhc_cmd   /*!< Signal name */

/* GPIO_SD_B0_02 (coord J1), SD1_D0 */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D0_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D0_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D0_CHANNEL                                         0U   /*!< Signal channel */

/* GPIO_SD_B0_03 (coord K1), SD1_D1 */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D1_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D1_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D1_CHANNEL                                         1U   /*!< Signal channel */

/* GPIO_SD_B0_04 (coord H2), SD1_D2 */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D2_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D2_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D2_CHANNEL                                         2U   /*!< Signal channel */

/* GPIO_SD_B0_05 (coord J2), SD1_D3 */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D3_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D3_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D3_CHANNEL                                         3U   /*!< Signal channel */

/* GPIO_AD_B1_00 (coord J11), ANT_BXX_CTS */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_CTS_PERIPHERAL                            LPUART2   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_CTS_SIGNAL                                  CTS_B   /*!< Signal name */

/* GPIO_AD_B1_01 (coord K11), ANT_BXX_RTS */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_RTS_PERIPHERAL                            LPUART2   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_RTS_SIGNAL                                  RTS_B   /*!< Signal name */

/* GPIO_AD_B1_03 (coord M12), ANT_BXX_RX */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_RX_PERIPHERAL                             LPUART2   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_RX_SIGNAL                                      RX   /*!< Signal name */

/* GPIO_AD_B1_02 (coord L11), ANT_BXX_TX */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_TX_PERIPHERAL                             LPUART2   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_TX_SIGNAL                                      TX   /*!< Signal name */

/* GPIO_AD_B1_12 (coord H12), ANT_BXX_CS */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_CS_PERIPHERAL                              LPSPI3   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_CS_SIGNAL                                    PCS0   /*!< Signal name */

/* GPIO_AD_B1_15 (coord J14), ANT_BXX_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_CLK_PERIPHERAL                             LPSPI3   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_CLK_SIGNAL                                    SCK   /*!< Signal name */

/* GPIO_AD_B1_13 (coord H11), ANT_BXX_MISO */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_MISO_PERIPHERAL                            LPSPI3   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_MISO_SIGNAL                                   SDI   /*!< Signal name */

/* GPIO_AD_B1_14 (coord G12), ANT_BXX_MOSI */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_MOSI_PERIPHERAL                            LPSPI3   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_MOSI_SIGNAL                                   SDO   /*!< Signal name */

/* GPIO_AD_B1_09 (coord M13), ANT_BXX_RST */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_RST_PERIPHERAL                              GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_RST_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ANT_BXX_RST_CHANNEL                                   25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ANT_BXX_RST_GPIO                                    GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_RST_GPIO_PIN                                  25U   /*!< GPIO pin number */
#define BOARD_INITPINS_ANT_BXX_RST_GPIO_PIN_MASK                     (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ANT_BXX_RST_PORT                                    GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_RST_PIN                                       25U   /*!< PORT pin number */
#define BOARD_INITPINS_ANT_BXX_RST_PIN_MASK                          (1U << 25U)   /*!< PORT pin mask */

/* GPIO_B1_12 (coord D13), ANT_BXX_SW1 */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_SW1_PERIPHERAL                              GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_SW1_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ANT_BXX_SW1_CHANNEL                                   28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ANT_BXX_SW1_GPIO                                    GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_SW1_GPIO_PIN                                  28U   /*!< GPIO pin number */
#define BOARD_INITPINS_ANT_BXX_SW1_GPIO_PIN_MASK                     (1U << 28U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ANT_BXX_SW1_PORT                                    GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_SW1_PIN                                       28U   /*!< PORT pin number */
#define BOARD_INITPINS_ANT_BXX_SW1_PIN_MASK                          (1U << 28U)   /*!< PORT pin mask */

/* GPIO_AD_B0_00 (coord M14), ANT_BXX_SW2 */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_SW2_PERIPHERAL                              GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_SW2_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ANT_BXX_SW2_CHANNEL                                    0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ANT_BXX_SW2_GPIO                                    GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_SW2_GPIO_PIN                                   0U   /*!< GPIO pin number */
#define BOARD_INITPINS_ANT_BXX_SW2_GPIO_PIN_MASK                      (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ANT_BXX_SW2_PORT                                    GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_SW2_PIN                                        0U   /*!< PORT pin number */
#define BOARD_INITPINS_ANT_BXX_SW2_PIN_MASK                           (1U << 0U)   /*!< PORT pin mask */

/* GPIO_AD_B1_10 (coord L13), ANT_BXX_GPIO1 */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_GPIO1_PERIPHERAL                            GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_GPIO1_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ANT_BXX_GPIO1_CHANNEL                                 26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ANT_BXX_GPIO1_GPIO                                  GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_GPIO1_GPIO_PIN                                26U   /*!< GPIO pin number */
#define BOARD_INITPINS_ANT_BXX_GPIO1_GPIO_PIN_MASK                   (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ANT_BXX_GPIO1_PORT                                  GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_GPIO1_PIN                                     26U   /*!< PORT pin number */
#define BOARD_INITPINS_ANT_BXX_GPIO1_PIN_MASK                        (1U << 26U)   /*!< PORT pin mask */

/* GPIO_AD_B1_11 (coord J13), ANT_BXX_GPIO2 */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_GPIO2_PERIPHERAL                            GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_GPIO2_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ANT_BXX_GPIO2_CHANNEL                                 27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ANT_BXX_GPIO2_GPIO                                  GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_GPIO2_GPIO_PIN                                27U   /*!< GPIO pin number */
#define BOARD_INITPINS_ANT_BXX_GPIO2_GPIO_PIN_MASK                   (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ANT_BXX_GPIO2_PORT                                  GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_GPIO2_PIN                                     27U   /*!< PORT pin number */
#define BOARD_INITPINS_ANT_BXX_GPIO2_PIN_MASK                        (1U << 27U)   /*!< PORT pin mask */

/* GPIO_AD_B1_08 (coord H13), ANT_BXX_GPIO3 */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_GPIO3_PERIPHERAL                            GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_GPIO3_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ANT_BXX_GPIO3_CHANNEL                                 24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ANT_BXX_GPIO3_GPIO                                  GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_GPIO3_GPIO_PIN                                24U   /*!< GPIO pin number */
#define BOARD_INITPINS_ANT_BXX_GPIO3_GPIO_PIN_MASK                   (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ANT_BXX_GPIO3_PORT                                  GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_GPIO3_PIN                                     24U   /*!< PORT pin number */
#define BOARD_INITPINS_ANT_BXX_GPIO3_PIN_MASK                        (1U << 24U)   /*!< PORT pin mask */

/* GPIO_EMC_36 (coord C3), ANT_BXX_UART_MUX */
/* Routed pin properties */
#define BOARD_INITPINS_ANT_BXX_UART_MUX_PERIPHERAL                         GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_ANT_BXX_UART_MUX_SIGNAL                           gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ANT_BXX_UART_MUX_CHANNEL                              22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ANT_BXX_UART_MUX_GPIO                               GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_UART_MUX_GPIO_PIN                             22U   /*!< GPIO pin number */
#define BOARD_INITPINS_ANT_BXX_UART_MUX_GPIO_PIN_MASK                (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ANT_BXX_UART_MUX_PORT                               GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ANT_BXX_UART_MUX_PIN                                  22U   /*!< PORT pin number */
#define BOARD_INITPINS_ANT_BXX_UART_MUX_PIN_MASK                     (1U << 22U)   /*!< PORT pin mask */

/* GPIO_SD_B1_00 (coord L5), MAYA_PDN */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_PDN_PERIPHERAL                                 GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_PDN_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MAYA_PDN_CHANNEL                                       0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAYA_PDN_GPIO                                       GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MAYA_PDN_GPIO_PIN                                      0U   /*!< GPIO pin number */
#define BOARD_INITPINS_MAYA_PDN_GPIO_PIN_MASK                         (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MAYA_PDN_PORT                                       GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MAYA_PDN_PIN                                           0U   /*!< PORT pin number */
#define BOARD_INITPINS_MAYA_PDN_PIN_MASK                              (1U << 0U)   /*!< PORT pin mask */

/* GPIO_EMC_04 (coord F2), MAYA_BT_W_H */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_BT_W_H_PERIPHERAL                              GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_BT_W_H_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MAYA_BT_W_H_CHANNEL                                    4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAYA_BT_W_H_GPIO                                    GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MAYA_BT_W_H_GPIO_PIN                                   4U   /*!< GPIO pin number */
#define BOARD_INITPINS_MAYA_BT_W_H_GPIO_PIN_MASK                      (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MAYA_BT_W_H_PORT                                    GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MAYA_BT_W_H_PIN                                        4U   /*!< PORT pin number */
#define BOARD_INITPINS_MAYA_BT_W_H_PIN_MASK                           (1U << 4U)   /*!< PORT pin mask */

/* GPIO_EMC_21 (coord C1), MAYA_BT_W_D */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_BT_W_D_PERIPHERAL                              GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_BT_W_D_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MAYA_BT_W_D_CHANNEL                                   21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAYA_BT_W_D_GPIO                                    GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MAYA_BT_W_D_GPIO_PIN                                  21U   /*!< GPIO pin number */
#define BOARD_INITPINS_MAYA_BT_W_D_GPIO_PIN_MASK                     (1U << 21U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MAYA_BT_W_D_PORT                                    GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MAYA_BT_W_D_PIN                                       21U   /*!< PORT pin number */
#define BOARD_INITPINS_MAYA_BT_W_D_PIN_MASK                          (1U << 21U)   /*!< PORT pin mask */

/* GPIO_EMC_27 (coord A2), MAYA_BT_RESET */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_BT_RESET_PERIPHERAL                            GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_BT_RESET_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MAYA_BT_RESET_CHANNEL                                 27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAYA_BT_RESET_GPIO                                  GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MAYA_BT_RESET_GPIO_PIN                                27U   /*!< GPIO pin number */
#define BOARD_INITPINS_MAYA_BT_RESET_GPIO_PIN_MASK                   (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MAYA_BT_RESET_PORT                                  GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MAYA_BT_RESET_PIN                                     27U   /*!< PORT pin number */
#define BOARD_INITPINS_MAYA_BT_RESET_PIN_MASK                        (1U << 27U)   /*!< PORT pin mask */

/* GPIO_EMC_28 (coord D1), MAYA_WLAN_W_H */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_WLAN_W_H_PERIPHERAL                            GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_WLAN_W_H_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MAYA_WLAN_W_H_CHANNEL                                 28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAYA_WLAN_W_H_GPIO                                  GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MAYA_WLAN_W_H_GPIO_PIN                                28U   /*!< GPIO pin number */
#define BOARD_INITPINS_MAYA_WLAN_W_H_GPIO_PIN_MASK                   (1U << 28U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MAYA_WLAN_W_H_PORT                                  GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MAYA_WLAN_W_H_PIN                                     28U   /*!< PORT pin number */
#define BOARD_INITPINS_MAYA_WLAN_W_H_PIN_MASK                        (1U << 28U)   /*!< PORT pin mask */

/* GPIO_EMC_09 (coord C2), MAYA_WLAN_W_D */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_WLAN_W_D_PERIPHERAL                            GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_WLAN_W_D_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MAYA_WLAN_W_D_CHANNEL                                  9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAYA_WLAN_W_D_GPIO                                  GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MAYA_WLAN_W_D_GPIO_PIN                                 9U   /*!< GPIO pin number */
#define BOARD_INITPINS_MAYA_WLAN_W_D_GPIO_PIN_MASK                    (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MAYA_WLAN_W_D_PORT                                  GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MAYA_WLAN_W_D_PIN                                      9U   /*!< PORT pin number */
#define BOARD_INITPINS_MAYA_WLAN_W_D_PIN_MASK                         (1U << 9U)   /*!< PORT pin mask */

/* GPIO_EMC_18 (coord B2), MAYA_WLAN_RESET */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_WLAN_RESET_PERIPHERAL                          GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_WLAN_RESET_SIGNAL                            gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MAYA_WLAN_RESET_CHANNEL                               18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAYA_WLAN_RESET_GPIO                                GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MAYA_WLAN_RESET_GPIO_PIN                              18U   /*!< GPIO pin number */
#define BOARD_INITPINS_MAYA_WLAN_RESET_GPIO_PIN_MASK                 (1U << 18U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MAYA_WLAN_RESET_PORT                                GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MAYA_WLAN_RESET_PIN                                   18U   /*!< PORT pin number */
#define BOARD_INITPINS_MAYA_WLAN_RESET_PIN_MASK                      (1U << 18U)   /*!< PORT pin mask */

/* GPIO_EMC_25 (coord D2), MAYA_TX */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_TX_PERIPHERAL                                LPUART6   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_TX_SIGNAL                                         TX   /*!< Signal name */

/* GPIO_EMC_26 (coord B3), MAYA_RX */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_RX_PERIPHERAL                                LPUART6   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_RX_SIGNAL                                         RX   /*!< Signal name */

/* GPIO_EMC_29 (coord E1), MAYA_RTS */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_RTS_PERIPHERAL                               LPUART6   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_RTS_SIGNAL                                     RTS_B   /*!< Signal name */

/* GPIO_EMC_30 (coord C6), MAYA_CTS */
/* Routed pin properties */
#define BOARD_INITPINS_MAYA_CTS_PERIPHERAL                               LPUART6   /*!< Peripheral name */
#define BOARD_INITPINS_MAYA_CTS_SIGNAL                                     CTS_B   /*!< Signal name */

/* GPIO_EMC_15 (coord B1), NINA_CTS */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_CTS_PERIPHERAL                               LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_CTS_SIGNAL                                     CTS_B   /*!< Signal name */

/* GPIO_EMC_16 (coord A5), NINA_RTS */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_RTS_PERIPHERAL                               LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_RTS_SIGNAL                                     RTS_B   /*!< Signal name */

/* GPIO_EMC_14 (coord B6), NINA_RX */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_RX_PERIPHERAL                                LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_RX_SIGNAL                                         RX   /*!< Signal name */

/* GPIO_EMC_13 (coord A6), NINA_TX */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_TX_PERIPHERAL                                LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_TX_SIGNAL                                         TX   /*!< Signal name */

/* GPIO_EMC_01 (coord F3), NINA_CS */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_CS_PERIPHERAL                                 LPSPI2   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_CS_SIGNAL                                       PCS0   /*!< Signal name */

/* GPIO_EMC_00 (coord E3), NINA_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_CLK_PERIPHERAL                                LPSPI2   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_CLK_SIGNAL                                       SCK   /*!< Signal name */

/* GPIO_EMC_03 (coord G4), NINA_MISO */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_MISO_PERIPHERAL                                GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_MISO_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_NINA_MISO_CHANNEL                                      3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NINA_MISO_GPIO                                      GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_NINA_MISO_GPIO_PIN                                     3U   /*!< GPIO pin number */
#define BOARD_INITPINS_NINA_MISO_GPIO_PIN_MASK                        (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_NINA_MISO_PORT                                      GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_NINA_MISO_PIN                                          3U   /*!< PORT pin number */
#define BOARD_INITPINS_NINA_MISO_PIN_MASK                             (1U << 3U)   /*!< PORT pin mask */

/* GPIO_EMC_02 (coord F4), NINA_MOSI */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_MOSI_PERIPHERAL                                GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_MOSI_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_NINA_MOSI_CHANNEL                                      2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NINA_MOSI_GPIO                                      GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_NINA_MOSI_GPIO_PIN                                     2U   /*!< GPIO pin number */
#define BOARD_INITPINS_NINA_MOSI_GPIO_PIN_MASK                        (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_NINA_MOSI_PORT                                      GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_NINA_MOSI_PIN                                          2U   /*!< PORT pin number */
#define BOARD_INITPINS_NINA_MOSI_PIN_MASK                             (1U << 2U)   /*!< PORT pin mask */

/* GPIO_EMC_22 (coord F1), NINA_RST */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_RST_PERIPHERAL                                 GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_RST_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_NINA_RST_CHANNEL                                      22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NINA_RST_GPIO                                       GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_NINA_RST_GPIO_PIN                                     22U   /*!< GPIO pin number */
#define BOARD_INITPINS_NINA_RST_GPIO_PIN_MASK                        (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_NINA_RST_PORT                                       GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_NINA_RST_PIN                                          22U   /*!< PORT pin number */
#define BOARD_INITPINS_NINA_RST_PIN_MASK                             (1U << 22U)   /*!< PORT pin mask */

/* GPIO_EMC_24 (coord D3), NINA_SW1 */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_SW1_PERIPHERAL                                 GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_SW1_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_NINA_SW1_CHANNEL                                      24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NINA_SW1_GPIO                                       GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_NINA_SW1_GPIO_PIN                                     24U   /*!< GPIO pin number */
#define BOARD_INITPINS_NINA_SW1_GPIO_PIN_MASK                        (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_NINA_SW1_PORT                                       GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_NINA_SW1_PIN                                          24U   /*!< PORT pin number */
#define BOARD_INITPINS_NINA_SW1_PIN_MASK                             (1U << 24U)   /*!< PORT pin mask */

/* GPIO_EMC_31 (coord C5), NINA_SW2 */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_SW2_PERIPHERAL                                 GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_SW2_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_NINA_SW2_CHANNEL                                      31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NINA_SW2_GPIO                                       GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_NINA_SW2_GPIO_PIN                                     31U   /*!< GPIO pin number */
#define BOARD_INITPINS_NINA_SW2_GPIO_PIN_MASK                        (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_NINA_SW2_PORT                                       GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_NINA_SW2_PIN                                          31U   /*!< PORT pin number */
#define BOARD_INITPINS_NINA_SW2_PIN_MASK                             (1U << 31U)   /*!< PORT pin mask */

/* GPIO_EMC_17 (coord A4), NINA_GPIO1 */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_GPIO1_PERIPHERAL                               GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_GPIO1_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_NINA_GPIO1_CHANNEL                                    17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NINA_GPIO1_GPIO                                     GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_NINA_GPIO1_GPIO_PIN                                   17U   /*!< GPIO pin number */
#define BOARD_INITPINS_NINA_GPIO1_GPIO_PIN_MASK                      (1U << 17U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_NINA_GPIO1_PORT                                     GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_NINA_GPIO1_PIN                                        17U   /*!< PORT pin number */
#define BOARD_INITPINS_NINA_GPIO1_PIN_MASK                           (1U << 17U)   /*!< PORT pin mask */

/* GPIO_EMC_20 (coord A3), NINA_GPIO2 */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_GPIO2_PERIPHERAL                               GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_GPIO2_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_NINA_GPIO2_CHANNEL                                    20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NINA_GPIO2_GPIO                                     GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_NINA_GPIO2_GPIO_PIN                                   20U   /*!< GPIO pin number */
#define BOARD_INITPINS_NINA_GPIO2_GPIO_PIN_MASK                      (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_NINA_GPIO2_PORT                                     GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_NINA_GPIO2_PIN                                        20U   /*!< PORT pin number */
#define BOARD_INITPINS_NINA_GPIO2_PIN_MASK                           (1U << 20U)   /*!< PORT pin mask */

/* GPIO_EMC_19 (coord B4), NINA_GPIO3 */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_GPIO3_PERIPHERAL                               GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_GPIO3_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_NINA_GPIO3_CHANNEL                                    19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NINA_GPIO3_GPIO                                     GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_NINA_GPIO3_GPIO_PIN                                   19U   /*!< GPIO pin number */
#define BOARD_INITPINS_NINA_GPIO3_GPIO_PIN_MASK                      (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_NINA_GPIO3_PORT                                     GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_NINA_GPIO3_PIN                                        19U   /*!< PORT pin number */
#define BOARD_INITPINS_NINA_GPIO3_PIN_MASK                           (1U << 19U)   /*!< PORT pin mask */

/* GPIO_EMC_33 (coord C4), NINA_UART_MUX */
/* Routed pin properties */
#define BOARD_INITPINS_NINA_UART_MUX_PERIPHERAL                            GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_NINA_UART_MUX_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_NINA_UART_MUX_CHANNEL                                 19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NINA_UART_MUX_GPIO                                  GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_NINA_UART_MUX_GPIO_PIN                                19U   /*!< GPIO pin number */
#define BOARD_INITPINS_NINA_UART_MUX_GPIO_PIN_MASK                   (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_NINA_UART_MUX_PORT                                  GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_NINA_UART_MUX_PIN                                     19U   /*!< PORT pin number */
#define BOARD_INITPINS_NINA_UART_MUX_PIN_MASK                        (1U << 19U)   /*!< PORT pin mask */

/* GPIO_B1_01 (coord B11), MCU_SW1 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SW1_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SW1_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SW1_CHANNEL                                       17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SW1_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SW1_GPIO_PIN                                      17U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SW1_GPIO_PIN_MASK                         (1U << 17U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SW1_PORT                                        GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SW1_PIN                                           17U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SW1_PIN_MASK                              (1U << 17U)   /*!< PORT pin mask */

/* GPIO_B1_02 (coord C11), MCU_SW2 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SW2_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SW2_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SW2_CHANNEL                                       18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SW2_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SW2_GPIO_PIN                                      18U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SW2_GPIO_PIN_MASK                         (1U << 18U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SW2_PORT                                        GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SW2_PIN                                           18U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SW2_PIN_MASK                              (1U << 18U)   /*!< PORT pin mask */

/* GPIO_B1_14 (coord C14), MCU_SW3 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SW3_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SW3_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SW3_CHANNEL                                       30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SW3_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SW3_GPIO_PIN                                      30U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SW3_GPIO_PIN_MASK                         (1U << 30U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SW3_PORT                                        GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SW3_PIN                                           30U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SW3_PIN_MASK                              (1U << 30U)   /*!< PORT pin mask */

/* GPIO_B1_00 (coord A11), USER_LED_01 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_LED_01_PERIPHERAL                              GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_USER_LED_01_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_LED_01_CHANNEL                                   16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_LED_01_GPIO                                    GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_LED_01_GPIO_PIN                                  16U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_LED_01_GPIO_PIN_MASK                     (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_USER_LED_01_PORT                                    GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_USER_LED_01_PIN                                       16U   /*!< PORT pin number */
#define BOARD_INITPINS_USER_LED_01_PIN_MASK                          (1U << 16U)   /*!< PORT pin mask */

/* GPIO_B1_15 (coord B14), USER_LED_02 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_LED_02_PERIPHERAL                              GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_USER_LED_02_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_LED_02_CHANNEL                                   31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_LED_02_GPIO                                    GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_LED_02_GPIO_PIN                                  31U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_LED_02_GPIO_PIN_MASK                     (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_USER_LED_02_PORT                                    GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_USER_LED_02_PIN                                       31U   /*!< PORT pin number */
#define BOARD_INITPINS_USER_LED_02_PIN_MASK                          (1U << 31U)   /*!< PORT pin mask */

/* WAKEUP (coord L6), USER_BUTTON */
/* Routed pin properties */
#define BOARD_INITPINS_USER_BUTTON_PERIPHERAL                              GPIO5   /*!< Peripheral name */
#define BOARD_INITPINS_USER_BUTTON_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_BUTTON_CHANNEL                                    0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_BUTTON_GPIO                                    GPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_BUTTON_GPIO_PIN                                   0U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_BUTTON_GPIO_PIN_MASK                      (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_USER_BUTTON_PORT                                    GPIO5   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_USER_BUTTON_PIN                                        0U   /*!< PORT pin number */
#define BOARD_INITPINS_USER_BUTTON_PIN_MASK                           (1U << 0U)   /*!< PORT pin mask */

/* PMIC_ON_REQ (coord K7), PMIC_ON_REQ */
/* Routed pin properties */
#define BOARD_INITPINS_PMIC_ON_REQ_PERIPHERAL                               SNVS   /*!< Peripheral name */
#define BOARD_INITPINS_PMIC_ON_REQ_SIGNAL                       snvs_pmic_on_req   /*!< Signal name */

/* GPIO_B1_13 (coord D14), WDOG_B */
/* Routed pin properties */
#define BOARD_INITPINS_WDOG_B_PERIPHERAL                                   WDOG1   /*!< Peripheral name */
#define BOARD_INITPINS_WDOG_B_SIGNAL                                      wdog_b   /*!< Signal name */

/* GPIO_AD_B0_10 (coord G13), INT1_COMBO */
/* Routed pin properties */
#define BOARD_INITPINS_INT1_COMBO_PERIPHERAL                               GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_INT1_COMBO_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_INT1_COMBO_CHANNEL                                    10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INT1_COMBO_GPIO                                     GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_INT1_COMBO_GPIO_PIN                                   10U   /*!< GPIO pin number */
#define BOARD_INITPINS_INT1_COMBO_GPIO_PIN_MASK                      (1U << 10U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_INT1_COMBO_PORT                                     GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_INT1_COMBO_PIN                                        10U   /*!< PORT pin number */
#define BOARD_INITPINS_INT1_COMBO_PIN_MASK                           (1U << 10U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
